import { ResumeData } from '@/types/resume';

export function exportToJson(state: ResumeData) {
  const jsonStr = JSON.stringify(state, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `resume-${state.profileName.replace(/\s+/g, '-').toLowerCase()}-backup.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportToLatex(state: ResumeData) {
  const latexStr = generateLatexString(state);
  const blob = new Blob([latexStr], { type: 'application/x-latex' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `resume-${state.profileName.replace(/\s+/g, '-').toLowerCase()}.tex`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function generateLatexString(state: ResumeData): string {
  const sanitize = (str: string) => {
    if (!str) return '';
    return str
      .replace(/\\/g, '\\\\')
      .replace(/&/g, '\\&')
      .replace(/%/g, '\\%')
      .replace(/\$/g, '\\$')
      .replace(/#/g, '\\#')
      .replace(/_/g, '\\_')
      .replace(/\{/g, '\\{')
      .replace(/\}/g, '\\}')
      .replace(/~/g, '\\textasciitilde')
      .replace(/\^/g, '\\textasciicircum');
  };

  const header = `%-------------------------
% Resume in Latex
% Generated by Resume Builder Pro
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.0in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titrule \\vspace{-5pt}]

\\pdfgentounicode=1

% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} \\textbar{} \\textit{\\small#2} & #3 \\\\
    \\end{tabular*}\\vspace{-7pt}
    \\ifx&#4&\\else
      \\vspace{2pt}\\small{#4}\\vspace{-5pt}
    \\fi
}

\\newcommand{\\resumeProjectProblem}[1]{\\vspace{2pt}\\small{\\textbf{Problem:} #1}}
\\newcommand{\\resumeProjectSolution}[1]{\\vspace{2pt}\\small{\\textbf{Solution:} #1}}
\\newcommand{\\resumeProjectLinks}[2]{
  \\ifx&#1&\\else\\href{#1}{GitHub}\\fi
  \\ifx&#1&\\else\\ifx&#2&\\else{} \\textbar{} \\fi\\fi
  \\ifx&#2&\\else\\href{#2}{Live Link}\\fi
}

\\newcommand{\\resumeCustomSectionStart}[2]{}
\\newcommand{\\resumeCustomSectionEnd}{}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

%===PERSONAL_INFO===
\\begin{center}
  \\textbf{\\Huge \\scshape ${sanitize(state.name)}} \\\\ \\vspace{1pt}
  \\small ${sanitize(state.title)} \\\\ \\vspace{1pt}
  \\small ${[
    state.phone ? `\\href{tel:${state.phone.replace(/[^\d+]/g, '')}}{${sanitize(state.phone)}}` : '',
    state.email ? `\\href{mailto:${state.email}}{${sanitize(state.email)}}` : '',
    state.linkedin ? `\\href{${state.linkedin.startsWith('http') ? state.linkedin : `https://${state.linkedin}`}}{LinkedIn}` : '',
    state.github ? `\\href{${state.github.startsWith('http') ? state.github : `https://${state.github}`}}{GitHub}` : '',
    state.website ? `\\href{${state.website.startsWith('http') ? state.website : `https://${state.website}`}}{Website}` : '',
    ...(state.customContacts || []).map(c => c.value ? `\\href{${c.value.startsWith('http') ? c.value : `https://${c.value}`}}{${sanitize(c.label)}}` : '')
  ].filter(Boolean).join(' \\textbar{} ')}
\\end{center}
`;

  let body = '';

  // Process sections in order
  state.sectionOrder.forEach((secKey) => {
    if (!state.secVis[secKey]) return;

    const title = state.secNames[secKey] || secKey;

    if (secKey === 'summary') {
      if (!state.summary) return;
      body += `\n%===SUMMARY===\n\\section{${sanitize(title)}}\n${sanitize(state.summary)}\n`;
    } 
    else if (secKey === 'education') {
      if (state.education.length === 0) return;
      body += `\n%===EDUCATION===\n\\section{${sanitize(title)}}\n\\resumeSubHeadingListStart\n`;
      state.education.forEach((edu) => {
        body += `  \\resumeSubheading
    {${sanitize(edu.school)}}{${sanitize(edu.dates)}}
    {${sanitize(edu.degree)}}{${sanitize(edu.gpa)}}\n`;
      });
      body += `\\resumeSubHeadingListEnd\n`;
    } 
    else if (secKey === 'experience') {
      if (state.experience.length === 0) return;
      body += `\n%===EXPERIENCE===\n\\section{${sanitize(title)}}\n\\resumeSubHeadingListStart\n`;
      state.experience.forEach((exp) => {
        body += `  \\resumeSubheading
    {${sanitize(exp.company)}}{${sanitize(exp.dates)}}
    {${sanitize(exp.role)}}{}\n`;
        if (exp.points && exp.points.length > 0) {
          body += `  \\resumeItemListStart\n`;
          exp.points.filter(Boolean).forEach((pt) => {
            body += `    \\resumeItem{${sanitize(pt)}}\n`;
          });
          body += `  \\resumeItemListEnd\n`;
        }
      });
      body += `\\resumeSubHeadingListEnd\n`;
    } 
    else if (secKey === 'projects') {
      if (state.projects.length === 0) return;
      body += `\n%===PROJECTS===\n\\section{${sanitize(title)}}\n\\resumeSubHeadingListStart\n`;
      state.projects.forEach((proj) => {
        const github = proj.githubUrl || '';
        const live = proj.liveUrl || '';
        body += `  \\resumeProjectHeading
    {${sanitize(proj.name)}}{${sanitize(proj.tech)}}{${sanitize(proj.dates)}}
    {\\resumeProjectLinks{${sanitize(github)}}{${sanitize(live)}}}\n`;
        if (proj.problemStatement) {
          body += `  \\resumeProjectProblem{${sanitize(proj.problemStatement)}}\n`;
        }
        if (proj.proposedSolution) {
          body += `  \\resumeProjectSolution{${sanitize(proj.proposedSolution)}}\n`;
        }
        if (proj.points && proj.points.length > 0) {
          body += `  \\resumeItemListStart\n`;
          proj.points.filter(Boolean).forEach((pt) => {
            body += `    \\resumeItem{${sanitize(pt)}}\n`;
          });
          body += `  \\resumeItemListEnd\n`;
        }
      });
      body += `\\resumeSubHeadingListEnd\n`;
    } 
    else if (secKey === 'skills') {
      if (state.skillGroups.length === 0) return;
      body += `\n%===SKILLS===\n\\section{${sanitize(title)}}\n\\begin{itemize}[leftmargin=0.15in, label={}]\n  \\small{\\item{\n`;
      state.skillGroups.forEach((sg, idx) => {
        body += `    \\textbf{${sanitize(sg.category)}}: {${sanitize(sg.values)}} ${idx < state.skillGroups.length - 1 ? '\\\\' : ''}\n`;
      });
      body += `  }}\n\\end{itemize}\n`;
    }
    else if (secKey.startsWith('custom_')) {
      const customSec = state.customSections[secKey];
      if (!customSec) return;
      
      body += `\n%===CUSTOM_SECTION:${secKey}===\n\\section{${sanitize(title)}}\n`;
      body += `\\resumeCustomSectionStart{${sanitize(title)}}{${customSec.type}}\n`;
      
      if (customSec.type === 'list' || customSec.type === 'simplelist') {
        const items = customSec.content.split('\n').filter(Boolean);
        body += `\\resumeItemListStart\n`;
        items.forEach((item) => {
          body += `  \\resumeItem{${sanitize(item)}}\n`;
        });
        body += `\\resumeItemListEnd\n`;
      } else {
        const lines = customSec.content.split('\n').map(sanitize).join('\\\\\n');
        body += `${lines}\n`;
      }
      
      body += `\\resumeCustomSectionEnd\n`;
    }
  });

  const footer = `\n\\end{document}\n`;

  return header + body + footer;
}
